SDCOSMO-1405 - fix platform upgrade script
Cosmo-Tech/azure-platform-deployment-tools pull request #31
Opened 2023-10-13 12:40 UTC by jpla-csm

2023-10-13 15:37 UTC, enocquet requested changes

2023-10-13 15:37 UTC, enocquet commented on deployment_scripts/v2.4/upgrade.sh
>      command: ["sh", "-c", "wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64", "-o", "/usr/bin/yq", "&&", "chmod", "+x", "/usr/bin/yq"]
I forgot this line yesterday. This is not used anymore since we removed the InitContainer. You can delete it too

2023-10-13 16:29 UTC, jpla-csm commented
Ok I just removed the whole dependencies container. Ready to merge.

2023-10-14 05:51 UTC, enocquet approved these changes

2023-10-23 09:14 UTC, merged